# Generated by Django 4.2.19 on 2025-07-20 18:36

from django.db import migrations

def add_user_games(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    UserGames = apps.get_model("users", "UserGames")
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        UserGames.objects.create(
            user=user,
            game="zone rush",
            apple_id="7f33b933ccb74651b833382c9a6c9e8c"
        )

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usergames"),
    ]

    operations = [
        migrations.RunPython(add_user_games, reverse_code=lambda apps, schema_editor: None),
    ]
