# Generated by Django 4.2.19 on 2025-07-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20250720_1942"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergames",
            name="apple_id",
            field=models.CharField(max_length=255),
        ),
    ]
