version: "3.11"

networks:
  default:
    name: psudilku-network
    external: true

volumes:
  pg-data:
  redis-data:

services:

  postgres:
    container_name: psudilku-postgres

    image: postgres:alpine

    volumes:
      - pg-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postg_user -d psudilku" ]
      interval: 1s
      timeout: 3s
      retries: 10

    env_file:
      - .env

  backend:
    container_name: psudilku-backend

    build: .

    volumes:
      - .:/app/

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy

  redis:
    container_name: psudilku-redis

    image: redis:alpine

    volumes:
      - redis-data:/data

    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 10
