# Generated by Django 4.2.19 on 2025-07-11 22:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phase10.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phase",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("code", models.CharField(default=phase10.models.generate_code, max_length=4, unique=True)),
                ("start", models.BooleanField(default=False)),
                (
                    "deck",
                    django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
                ),
                (
                    "discard",
                    django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PhasePlayers",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("level", models.IntegerField(default=1)),
                (
                    "hand",
                    django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
                ),
                ("complete", models.JSONField(default=list)),
                ("active", models.BooleanField(default=True)),
                ("current_queue", models.BooleanField(default=False)),
                ("finish_level", models.BooleanField(default=False)),
                ("finish_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="players", to="phase10.phase"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
