# Generated by Django 4.2.19 on 2025-06-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase10", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phaseplayers",
            name="finish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
