# Generated by Django 4.2.19 on 2025-07-11 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("phase10", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="phaseplayers",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="phase",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="phase_game", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
