# Generated by Django 4.2.19 on 2025-07-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase10", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="phaseplayers",
            name="order_queue",
            field=models.IntegerField(default=0),
        ),
    ]
