# Generated by Django 4.2.19 on 2025-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase10", "0003_phaseplayers_order_queue"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="round",
            field=models.IntegerField(default=1),
        ),
    ]
