# Generated by Django 4.2.19 on 2025-08-11 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("phase10", "0004_phase_round"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="level_config",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="PhaseCustomLevels",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("name", models.CharField(max_length=100)),
                ("config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
