# Generated by Django 4.2.19 on 2025-08-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase10", "0005_phase_level_config_phasecustomlevels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phaseplayers",
            name="level",
            field=models.IntegerField(default=0),
        ),
    ]
