# Generated by Django 4.2.19 on 2025-08-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase10", "0006_alter_phaseplayers_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="duration",
            field=models.IntegerField(default=60),
        ),
    ]
