# Generated by Django 4.2.19 on 2025-08-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase10", "0007_phase_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="change_queue_time",
            field=models.DateTimeField(null=True),
        ),
    ]
