# Generated by Django 4.2.19 on 2025-08-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase10", "0008_phase_change_queue_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phase",
            name="change_queue_time",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
