# Generated by Django 4.2.19 on 2025-08-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase10", "0009_alter_phase_change_queue_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="phaseplayers",
            name="get_card",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="phaseplayers",
            name="put_card",
            field=models.BooleanField(default=False),
        ),
    ]
