# Generated by Django 4.2.19 on 2025-08-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase10", "0010_phaseplayers_get_card_phaseplayers_put_card"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phasecustomlevels",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="phaseplayers",
            options={"ordering": ["order_queue"]},
        ),
        migrations.RemoveField(
            model_name="phase",
            name="start",
        ),
        migrations.AddField(
            model_name="phase",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("started", "Started"), ("finished", "Finished")], default="pending"
            ),
        ),
    ]
