# Generated by Django 4.2.19 on 2025-08-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phase10", "0011_alter_phasecustomlevels_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phaseplayers",
            old_name="active",
            new_name="connected",
        ),
        migrations.AddField(
            model_name="phaseplayers",
            name="in_game",
            field=models.BooleanField(default=True),
        ),
    ]
