# Generated by Django 4.2.19 on 2025-08-30 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phase10", "0012_rename_active_phaseplayers_connected_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phasecustomlevels",
            options={},
        ),
        migrations.AlterModelOptions(
            name="phaseplayers",
            options={},
        ),
    ]
