# Generated by Django 4.2.19 on 2025-08-04 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid
import whoiam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhoIam",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("code", models.CharField(default=whoiam.models.generate_code, max_length=4, unique=True)),
                ("start", models.BooleanField(default=False)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="who_iam_game",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WhoIamPlayers",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("system_created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("active", models.BooleanField(default=True)),
                ("complete", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("word", models.CharField(max_length=100)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "whoiam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="players", to="whoiam.whoiam"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
