# Generated by Django 4.2.19 on 2025-08-04 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("whoiam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whoiam",
            name="pending",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="whoiamplayers",
            name="create_word",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whoiamplayers",
            name="for_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="who_iam_for_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="whoiamplayers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="who_iam_user", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="whoiamplayers",
            name="word",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
