# Generated by Django 4.2.19 on 2025-08-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whoiam", "0002_whoiam_pending_whoiamplayers_create_word_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whoiamplayers",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
